### ISSUE TITLE
soplex 7.0.0: Test suite failures (`...-mps-exact-pure-boosting`) on numerous platforms

### ISSUE THREAD

**Issue by mkoeppe** [scipopt/soplex#35]
For example https://github.com/scipopt/SCIP-SDP/actions/runs/8091622924/job/22110987857#step:11:3623
```
  [soplex-7.0.0]   The following tests FAILED:
  [soplex-7.0.0]   	 99 - etamacro-mps-exact-pure-boosting (NUMERICAL)
  [soplex-7.0.0]   	385 - refinery-mps-exact-pure-boosting (NUMERICAL)
  [soplex-7.0.0]   	407 - gas11-mps-exact-pure-boosting (NUMERICAL)
  [soplex-7.0.0]   Errors while running CTest
  [soplex-7.0.0]   Output from these tests are in: /sage/local/var/tmp/sage/build/soplex-7.0.0/src/build/Testing/Temporary/LastTest.log
  [soplex-7.0.0]   Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
  [soplex-7.0.0]   make[3]: *** [Makefile:91: test] Error 8
```

This is from a run of the SageMath portability tests in https://github.com/scipopt/SCIP-SDP/pull/13

(If there is interest, I can send a PR to add this GH Actions workflow to Soplex.)

**Comment by leoneifler** [comment]
That is interesting. Is there a full log available? It seems that all necessary libraries are installed and I don´t have that problem when running locally. I am not sure how best to debug this.

I would say there is definitely interest to have this GH actions workflow for Soplex,

**Comment by mkoeppe** [comment]
> Is there a full log available?

I'll add `--rerun-failed --output-on-failure` to the script as the message above suggests.

> I am not sure how best to debug this.

When invoked directly (does not work on PRs because of permissions), this CI workflow pushes Docker images of all builds to ghcr.io

**Comment by Mizux** [comment]
would be better to reuse the scip workflow https://github.com/scipopt/scip/blob/master/.github/workflows/build_and_test.yml imho

But adapt it a little:
```yml
   steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git g++ make cmake libgmp-dev libreadline-dev libncurses-dev libboost-all-dev zlib1g-dev libzstd-dev
      - uses: actions/checkout@v7
      - name: Check CMake
        run: cmake --version
      - name: Configure
        run: cmake -S. -Bbuild -DCMAKE_INSTALL_PREFIX=install
      - name: Build
        run: cmake --build build --target all -v -j2
      - name: Test
        run: >
          CTEST_OUTPUT_ON_FAILURE=1
          cmake --build build
          --target test
          -v
      - name: Install
        run: >
          cmake --build build
          --target install
          -v
```
ref: https://github.com/Mizux/soplex/blob/cmake/ci/.github/workflows/amd64_linux_cmake.yml

note: prefer to use `cmake -S. -Bbuild` (than using `mkdir build && cd build && cmake ..`)
ref: https://cmake.org/cmake/help/latest/manual/cmake.1.html#generate-a-project-buildsystem

note: you should also add a `dependabot.yml` to keep your actions up to date (e.g checkout@v2 while @v7 is already out...)
see: https://github.com/Mizux/scip/blob/bazel/v10.0.3/.github/dependabot.yml
